all: Refactor the whole kdump/pstore folder setting
This is somewhat a big refactor. The early design of kdump/pstore was
meant to support the A/B scheme of Steam Deck and a dracut-based initrd
only. In this scheme, we had a DEVNODE (like nvme partition or a devlink)
that represented the device node to be mounted early in boot when kdump
was in use. Also, we had a folder defined in the config file on top of
such dev node, and a temporary file used to "carry" the composition of
the full kdump path across boot time scripts. Yeah, kinda complex setup.

We are now moving to a more generic approach, and for that, the design
choice was a more convenient/simple one for the common cases, that
requires some operations to properly work on SteamOS dracut-based initrd.
Now we have only a single path on config file, which should be accessible
in a R/W filesystem by both scripts executed in the systemd service. No
devnode information or temp file is used anymore.

But with that, comes the need of discovering the proper devnode and base
folder for kdump'ing early in boot, from the initrd. Using the findmnt
tool we manage to derive all the necessary data during the initrd
preparation phase. Also, while at it we manage to fix an "inconsistency"
of our dracut initrd creation script: installkernel() should be responsible
to deal with DRM modules removal, not install().

On top of this (already big) change, now our dracut initrd excludes not
only amdgpu driver/FWs, but radeon, nvidia and i915 as well. And due to
our refactor of the mount point information (using findmnt to collect info
during dracut initrd creation), we also allow now arbitrary filesystem
drivers to be included, i.e., we don't hardcode/limit for ext4 only.

Again, mea culpa for not splitting this in multiple atomic/simple commits,
the burden to keep a pretty git log is starting to consume precious time.

Signed-off-by: Guilherme G. Piccoli <gpiccoli@igalia.com>

diff --git a/module-setup.sh.in b/module-setup.sh.in
--- a/module-setup.sh.in
+++ b/module-setup.sh.in
@@ -4,39 +4,60 @@ check() {
 }
 
 installkernel() {
-	hostonly='' instmods ext4
+	load_kdump_config
+
+	#  First clear all unnecessary firmwares/drivers added by drm in order
+	#  to reduce the size of the minimal initramfs being created - kdump
+	#  is an non-graphical environment. This should have been already done
+	#  via dracut cmdline arguments, but play safe and delete here as well.
+	#  Our list include the most common FWs/drivers (amd, i915, nvidia)
+	rm -rf "$initdir"/usr/lib/firmware/{amdgpu,i915,nvidia,radeon}
+	rm -rf "$initdir"/usr/lib/modules/*/kernel/drivers/gpu/drm/{amd,i915,nouveau,radeon}
+
+	FSMOD="$(findmnt -n -o FSTYPE --target "${MOUNT_FOLDER}")"
+	if [ -z "${FSMOD}" ]; then
+		logger "kdump: error on filesystem discovery"
+		exit 1
+	fi
+
+	hostonly='' instmods "${FSMOD}"
 }
 
 install() {
 	# A valid makedumpfile is essential for the kdump initrd creation.
 	if [ ! -x "$(command -v makedumpfile)" ]; then
-		logger "kdump: failed to create initrd, makedumpfile is missing"
+		logger "kdump: failed to create dracut initrd, makedumpfile is missing"
 		exit 1
 	fi
 
 	load_kdump_config
-
-	#  First clear all unnecessary firmwares/drivers added by drm in order
-	#  to reduce the size of the minimal initramfs being created. This
-	#  should be already done via dracut cmdline arguments, but let's play
-	#  safe and delete from here as well just in case.
-	rm -rf "$initdir"/usr/lib/firmware/amdgpu/
-	rm -rf "$initdir"/usr/lib/modules/*/kernel/drivers/gpu/drm/amd/*
 
 	#  Install necessary binaries
 	inst date
 	inst sync
 	inst makedumpfile
 
-	mkdir -p "$initdir"/usr/share/kdump.d/
-	cp -LR --preserve=all /usr/share/kdump.d/* "$initdir"/usr/share/kdump.d/
+	#  Copying kdump config/lib files is essential for a functional kdump.
+	cp -LR --preserve=all /usr/share/kdump.d/ "$initdir"/usr/share/
+	cp -LR --preserve=all /usr/lib/kdump/ "$initdir"/usr/lib/
 
-	#  Determine the numerical devnode for kdump, and save it on initrd;
-	#  notice that partset link is not available that early in boot time.
-	DEVN="$(readlink -f "${MOUNT_DEVNODE}")"
-	echo "${DEVN}" > "$initdir"/usr/lib/kdump/kdump.devnode
+	#  Finally, we need to derive the proper place to save the dump from the
+	#  config files, in a way that makes possible to mount it in early boot.
+	DEVNODE="$(findmnt -n -o SOURCE --target "${MOUNT_FOLDER}")"
+	if [ -z "${DEVNODE}" ]; then
+		logger "kdump: error on devnode discovery"
+		exit 1
+	fi
+	echo "${DEVNODE}" > "$initdir"/usr/lib/kdump/kdump.mnt
 
-	cp -LR --preserve=all /usr/lib/kdump/* "$initdir"/usr/lib/kdump/
+	TGT="$(findmnt -n -o TARGET --target "${MOUNT_FOLDER}")"
+	if [ -z "${TGT}" ]; then
+		logger "kdump: error on base folder discovery"
+		exit 1
+	fi
+
+	BASE_FLD="${MOUNT_FOLDER#*$TGT}"
+	echo "${BASE_FLD}" > "$initdir"/usr/lib/kdump/kdump.dir
 
 	inst_hook pre-mount 01 "$moddir/kdump-collect.sh"
 }
